### PR TITLE
Removed unused CSS properties

### PR DESCRIPTION
**Pull request by fregante**
Question-PR: why were those properties set?

`visibility:hidden` already "includes" `opacity:0` and `pointer-events:none`.

The actual iframe size is not relevant to the purpose, from what I understand, so whether the iframe has `border`s or `margin`s shouldn't affect the behavior.

`position: absolute` already pulls the element out of the flow. Positioning doesn't change its `width`/`height`

### CODE REVIEW

**Comment by developit** [comment]
The iframe needs to have a size relative to its parent (percentage) in order to trigger resize events. Any value less than 100% could (I haven't checked) skip subpixel size changes based on the scaling factor.  I agree we could drop `left:0`, but `top:-100%` is important for preventing the iframe from sitting in front of content.  In browsers that don't support `pointer-events:none` (esp for iframes, which don't inherit that given they are a new document context) this would prevent user interaction in the element being observed.  Opacity can be dropped too, I think I had it in there from before I realized `visibility:hidden` still allowed resize events in the framed document.

As for the border and margin, those are included in order to prevent the iframe from triggering overflow scrolling in the element its sitting inside of.  The default border combined with width:100% would trigger scrollbars.

**Comment by fregante** [comment]
- width/height weren't touched
- `pointer-events` isn't used, because there's already `visibility: hidden`
- same for `top`; its calculated position is still going to be hidden
- you're right about margin/border; but then, what's that `margin:1px 0 0`?

**Comment by NekR** [comment]
I really think `top: -100%` should be there. If it it doesn't affect rendering, it still puts iframe on top of the elements in container and when you need to inspect elements (via DevTools) in that container you always will be selection the iframe.

Also `pointer-events: none` makes DevTools ignore elements from selection via inspect-selection. Might be useful to leave it there too. Although not much important as `top: -100%`.

**Comment by developit** [comment]
The `margin:1px 0 0` is required in order to keep at least 1px of the iframe from being clipped. If fully clipped (top:-100%), resize events are throttled or ignored entirely as the iframe is considered off-canvas.

**Comment by NekR** [comment]
Apparently even current CSS-set makes Firefox to not fire resize events. Reducing it to
```
position:absolute;left:0;top:0;width:100%;height:100%;margin:0;border:none;pointer-events:none;opacity:0;
```
makes Firefox fire resize events again.

**Comment by developit** [comment]
@NekR I think it's visibility causing that.

**Comment by NekR** [comment]
Okay, it's much simpler -- removing `visibility:hidden` makes it fire resize events. Probably add `pointer-events:none` when supported and if not add `visiblity:hidden`?

**Comment by NekR** [comment]
@developit yeah, was going to try css props one by one and it was the `visibility`.

**Comment by NekR** [comment]
Okay, in my local version I just implemented it with pointer-events || visibility and it works fine. Any opinions against such solution?

**Comment by developit** [comment]
@NekR how'd you do the detection?  I'd be fine with `opacity:0;pointer-events:none;` and no visibility property at all.

**Comment by NekR** [comment]
@developit 

```js
let pointerEvents = document.documentMode < 11 ? false : 'pointerEvents' in style;
```

IE prior 11 has `pointer-events` only for SVG elements but reports them for HTML elements too. So detect IE first and then check for property existence.

> and no visibility property at all.
If iframe is going to be always off-screen then probably fine. Otherwise it will be clickable in IE.

**Comment by developit** [comment]
I wonder... do you think we could detect text direction and do `left/right:-100%`?  Then there'd only be a 1x1 element clickable in IE.

**Comment by NekR** [comment]
> do you think we could detect text direction 

I think that will be much harder than pointer-events. What's wrong with pointer-events detection? With `top: -100%` it's 100%/1px clickable element, right?

**Comment by fregante** [comment]
How about `z-index:-1;opacity:0.00001`?

**Comment by developit** [comment]
@NekR nothing wrong, just spitballing :P
@bfred-it think it works across chrome/firefox/IE/safari?

**Comment by fregante** [comment]
Needs testing. I'll try a jsfiddle later

**Comment by NekR** [comment]
Full opacity should be faster than such `0.00001` thing, right?

**Comment by fregante** [comment]
Yeah I'm just trying to keep the browser from optimizing it *out*. It might not be necessary

**Comment by NekR** [comment]
I have this in my code and I already tried -- it works. So I would suggest to have something like it:

```js
observeTree() {
  console.log('observe');
  this.iframe = document.createElement('iframe');

  let cssText = 'position:absolute;left:0;top:-100%;width:100%;height:100%;margin:1px 0 0;border:none;opacity:0;pointer-events:none;';

  if (!CSSProps.pointerEvents) {
    cssText += 'visibility:hidden;';
  }

  this.iframe.style.cssText = cssText;
  this.refs.inner.appendChild(this.iframe);
  this.iframe.contentWindow.onresize = this.onViewResize;
}
```

**Comment by fregante** [comment]
@developit I saw you have rollup-es3 in there, are you supporting IE8? Just wondering if that needs testing as well

**Comment by developit** [comment]
@bfred-it Nah, it's just to get rid of Rollup's `Object.freeze` and stuff (pointless for most libs).

@NekR can maybe abuse the iframe to inspect style support:

```js
if (document.documentMode<11 && !('pointerEvents' in iframe.style)) {
  iframe.style.visibility = 'hidden';
}
```

**Comment by NekR** [comment]
Yeah, exactly. In my project I just have inspection lib/helper, so made it
there.

**Comment by developit** [comment]
This is still on my radar btw, sorry for the lag time. Need to do a bunch of cross-browser testing before we can merge.

**Pull request closed without merging**
