### PR TITLE
Fix Firefox visiblity issue

### LINKED ISSUE #6: Don't work in firefox
It don't work in Firefox, the event is not fired when there is `visibility:hidden`. If you remove it it's fired.

### PR DESCRIPTION
**Pull request by NekR**
Fixes #6. I use this solution in production.

### CODE REVIEW

**Comment by NekR** [comment]
Oops. Bad copy-paste..

**Comment by NekR** [comment]
@developit I'm checking for `pointerEvents` in `document.documentElement` right now, but we can move everything to the exported function and then it will be possible to check on the iframe. Or at least move PE check in there.

What do you think?

**Comment by NekR** [comment]
Okay, I actually went ahead with the best way I think it would be. Sorry for the spam..

**Comment by NekR** [comment]
@developit ping?

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
this is one of my slowest PR reviews

**Pull request merged**
